### ISSUE TITLE
Place all admin-dialogs in AngularJS and REST, remove dependency on ASPX

### ISSUE THREAD

**Issue by iJungleboy** [2sic/eav#21]
Would also fix all issues with DNN urls in admin dialogs 2sic/2sxc#258

**Comment by BeniGemperle** [comment]
ToDo:
1. Content Types List: Grid of Attribute Sets, Filter System-Types, 5 command-links
2. Add Content Type
3. Content Type fields: List of fields, 4 Command Links
4. Content Type Edit/Add
5. Items Grid

**Comment by iJungleboy** [comment]
all done since 2sxc 8 / eav 4.2...
