### ISSUE TITLE
CSV Data Source cannot automatically take a title...

### ISSUE THREAD

**Issue by iJungleboy** [2sic/eav#26]
leaving the title blank should automatically take some column - but it doesn't. Current behaviour is that it then wants a column called "Title" - so it fails if this is not found. Pls fix so it "always works" - basically if there is a Title column that would be ok, but in general it should always work - so maybe using the first column etc. would be the correct behaviour - at least if a default "title" isn't found

**Comment by tobias2sic** [comment]
Done.
